## Timing Assertions Section

set_property IOSTANDARD LVDS  [get_ports sys0_clkp]
set_property PACKAGE_PIN AD12 [get_ports sys0_clkp]
set_property IOSTANDARD LVDS  [get_ports sys0_clkn]
set_property PACKAGE_PIN AD11 [get_ports sys0_clkn]
set_property IOSTANDARD LVCMOS15  [get_ports sys0_rst]
set_property PACKAGE_PIN AB7 [get_ports sys0_rst]
create_clock -name sys0_clkp -period 8 -waveform {0 4} [get_ports sys0_clkp]

set_property PACKAGE_PIN G8 [get_ports sys1_clkp]
set_property PACKAGE_PIN G7 [get_ports sys1_clkn]
create_clock -name sys1_clkp -period 8 -waveform {0 4} [get_ports sys1_clkp]

## Timing Exceptions Section


## Physical Constraints Section

## led constraints
set_property PACKAGE_PIN AB8 [get_ports led[0]]
set_property IOSTANDARD LVCMOS15  [get_ports led[0]]
set_property SLEW SLOW [get_ports led[0]]
set_property DRIVE 4 [get_ports led[0]]
set_property PACKAGE_PIN AA8 [get_ports led[1]]
set_property IOSTANDARD LVCMOS15  [get_ports led[1]]
set_property SLEW SLOW [get_ports led[1]]
set_property DRIVE 4 [get_ports led[1]]
set_property PACKAGE_PIN AC9 [get_ports led[2]]
set_property IOSTANDARD LVCMOS15  [get_ports led[2]]
set_property SLEW SLOW [get_ports led[2]]
set_property DRIVE 4 [get_ports led[2]]
set_property PACKAGE_PIN AB9 [get_ports led[3]]
set_property IOSTANDARD LVCMOS15  [get_ports led[3]]
set_property SLEW SLOW [get_ports led[3]]
set_property DRIVE 4 [get_ports led[3]]
set_property PACKAGE_PIN AE26 [get_ports led[4]]
set_property IOSTANDARD LVCMOS15  [get_ports led[4]]
set_property SLEW SLOW [get_ports led[4]]
set_property DRIVE 4 [get_ports led[4]]
set_property PACKAGE_PIN G19 [get_ports led[5]]
set_property IOSTANDARD LVCMOS15  [get_ports led[5]]
set_property SLEW SLOW [get_ports led[5]]
set_property DRIVE 4 [get_ports led[5]]
set_property PACKAGE_PIN E18 [get_ports led[6]]
set_property IOSTANDARD LVCMOS15  [get_ports led[6]]
set_property SLEW SLOW [get_ports led[6]]
set_property DRIVE 4 [get_ports led[6]]
set_property PACKAGE_PIN F16 [get_ports led[7]]
set_property IOSTANDARD LVCMOS15  [get_ports led[7]]
set_property SLEW SLOW [get_ports led[7]]
set_property DRIVE 4 [get_ports led[7]]
#
### lcd constraints
#set_property LOC Y10 [get_ports lcd_db[3]]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_db[3]]
#set_property SLEW SLOW [get_ports lcd_db[3]]
#set_property DRIVE 4 [get_ports lcd_db[3]]
#set_property LOC AA11 [get_ports lcd_db[2]]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_db[2]]
#set_property SLEW SLOW [get_ports lcd_db[2]]
#set_property DRIVE 4 [get_ports lcd_db[2]]
#set_property LOC AA10 [get_ports lcd_db[1]]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_db[1]]
#set_property SLEW SLOW [get_ports lcd_db[1]]
#set_property DRIVE 4 [get_ports lcd_db[1]]
#set_property LOC AA13 [get_ports lcd_db[0]]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_db[0]]
#set_property SLEW SLOW [get_ports lcd_db[0]]
#set_property DRIVE 4 [get_ports lcd_db[0]]
#set_property LOC AB10 [get_ports lcd_e]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_e]
#set_property SLEW SLOW [get_ports lcd_e]
#set_property DRIVE 4 [get_ports lcd_e]
#set_property LOC Y11 [get_ports lcd_rs]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_rs]
#set_property SLEW SLOW [get_ports lcd_rs]
#set_property DRIVE 4 [get_ports lcd_rs]
#set_property LOC AB13 [get_ports lcd_rw]
#set_property IOSTANDARD LVCMOS15  [get_ports lcd_rw]
#set_property SLEW SLOW [get_ports lcd_rw]
#set_property DRIVE 4 [get_ports lcd_rw]

## gmac phy constraints
set_property IOSTANDARD LVCMOS25 [get_ports gmii_txd*]
set_property PACKAGE_PIN N27 [get_ports gmii_txd[0]]
set_property PACKAGE_PIN N25 [get_ports gmii_txd[1]]
set_property PACKAGE_PIN M29 [get_ports gmii_txd[2]]
set_property PACKAGE_PIN L28 [get_ports gmii_txd[3]]
set_property PACKAGE_PIN J26 [get_ports gmii_txd[4]]
set_property PACKAGE_PIN K26 [get_ports gmii_txd[5]]
set_property PACKAGE_PIN L30 [get_ports gmii_txd[6]]
set_property PACKAGE_PIN J28 [get_ports gmii_txd[7]]

set_property IOSTANDARD LVCMOS25 [get_ports gmii_tx_en]
set_property PACKAGE_PIN M27 [get_ports gmii_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_tx_er]
set_property PACKAGE_PIN N29 [get_ports gmii_tx_er]

set_property IOSTANDARD LVCMOS25 [get_ports gmii_rxd*]
set_property PACKAGE_PIN U30 [get_ports gmii_rxd[0]]
set_property PACKAGE_PIN U25 [get_ports gmii_rxd[1]]
set_property PACKAGE_PIN T25 [get_ports gmii_rxd[2]]
set_property PACKAGE_PIN U28 [get_ports gmii_rxd[3]]
set_property PACKAGE_PIN R19 [get_ports gmii_rxd[4]]
set_property PACKAGE_PIN T27 [get_ports gmii_rxd[5]]
set_property PACKAGE_PIN T26 [get_ports gmii_rxd[6]]
set_property PACKAGE_PIN T28 [get_ports gmii_rxd[7]]

set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_dv]
set_property PACKAGE_PIN R28 [get_ports gmii_rx_dv]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_er]
set_property PACKAGE_PIN V26 [get_ports gmii_rx_er]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_clk]
set_property PACKAGE_PIN U27 [get_ports gmii_rx_clk]
#
#
set_property IOSTANDARD LVCMOS25 [get_ports gmii_col]
set_property PACKAGE_PIN W19 [get_ports gmii_col]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_crs]
set_property PACKAGE_PIN R30 [get_ports gmii_crs]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_intr]
set_property PACKAGE_PIN N30 [get_ports gmii_intr]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdc]
set_property PACKAGE_PIN R23 [get_ports mdio_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdd]
set_property PACKAGE_PIN J21 [get_ports mdio_mdd]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rstn]
set_property PACKAGE_PIN L20 [get_ports gmii_rstn]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_gtx_clk]
set_property PACKAGE_PIN K30 [get_ports gmii_gtx_clk]

create_clock -name GMII_RX_CLK -period 8 -waveform {0 4} [get_ports gmii_rx_clk]
set_input_delay -clock GMII_RX_CLK -max 5.5 [get_ports gmii_rxd*]
set_input_delay -clock GMII_RX_CLK -min 0.5 [get_ports gmii_rxd*]
set_input_delay -clock GMII_RX_CLK -max 5.5 [get_ports gmii_rx_dv]
set_input_delay -clock GMII_RX_CLK -min 0.5 [get_ports gmii_rx_dv]
set_input_delay -clock GMII_RX_CLK -max 5.5 [get_ports gmii_rx_er]
set_input_delay -clock GMII_RX_CLK -min 0.5 [get_ports gmii_rx_er]

# These gmii_TX signals are source-synchronous to gmii_gtx_clk
# Their output-delay is not important. They must be skew-matched to txRS_iobTxClk
#create_clock -name GMII_GTX_CLK -period 8 -waveform {0 4} [get_ports sys1_clkp]
create_clock -name GMII_GTX_CLK -period 8 -waveform {0 4} [get_ports gmii_gtx_clk]
#set_output_delay -clock GMII_GTX_CLK 2 [get_ports gmii_txd*]
#set_output_delay -clock GMII_GTX_CLK 2 [get_ports gmii_tx_en]
#set_output_delay -clock GMII_GTX_CLK 2 [get_ports gmii_tx_er]

